//! KEL merge engine — verification, divergence detection, recovery, contest, adversary archival.
//!
//! Provides the core merge logic used by all write paths. Every database-backed
//! repository funnels through [`MergeTransaction::merge_events`] so that gossip,
//! federation, and direct submissions all receive full verification and divergence
//! handling.

use std::collections::{HashMap, HashSet};
use std::iter;
use std::slice;

use async_trait::async_trait;
use cesr::{Matter, Signature};
use tracing::debug;
use verifiable_storage::{Delete, Order, Query, SelfAddressed, TransactionExecutor};

use crate::{
    BranchTip, EventKind, EventSignature, KelMergeResult, KelVerification, KelVerifier,
    KelsAuditRecord, KelsError, KeyEvent, SignedKeyEvent, completed_verification,
    load_signed_history, repository::zip_events_with_signatures, types::PageLoader,
};

/// Outcome of a merge operation.
#[derive(Debug, Clone)]
pub struct MergeOutcome {
    pub result: KelMergeResult,
    pub diverged_at: Option<u64>,
    pub tip_said: Option<String>,
}

impl MergeOutcome {
    pub fn empty() -> Self {
        Self {
            result: KelMergeResult::Accepted,
            diverged_at: None,
            tip_said: None,
        }
    }
}

/// Transaction wrapper for KEL merge operations.
///
/// Wraps a [`TransactionExecutor`] (e.g. a PostgreSQL transaction) with table
/// name configuration and provides all the database operations the merge engine
/// needs. Created by `begin_merge_transaction` (generated by the `SignedEvents`
/// derive macro).
pub struct MergeTransaction<T: TransactionExecutor> {
    tx: T,
    prefix: String,
    events_table: &'static str,
    signatures_table: &'static str,
    audit_table: Option<&'static str>,
}

impl<T: TransactionExecutor> MergeTransaction<T> {
    pub fn new(
        tx: T,
        prefix: String,
        events_table: &'static str,
        signatures_table: &'static str,
        audit_table: Option<&'static str>,
    ) -> Self {
        Self {
            tx,
            prefix,
            events_table,
            signatures_table,
            audit_table,
        }
    }

    pub fn prefix(&self) -> &str {
        &self.prefix
    }

    // ==================== Assembly helpers ====================

    /// Fetch signatures for a single event and return as `SignedKeyEvent`.
    async fn assemble_signed_event(
        &mut self,
        event: KeyEvent,
    ) -> Result<SignedKeyEvent, KelsError> {
        let query =
            Query::<EventSignature>::for_table(self.signatures_table).eq("event_said", &event.said);
        let signatures: Vec<EventSignature> = self.tx.fetch(query).await?;
        let sig_map = HashMap::from([(event.said.clone(), signatures)]);
        zip_events_with_signatures(vec![event], &sig_map).map(|mut v| v.remove(0))
    }

    /// Fetch signatures for a batch of events and return as `Vec<SignedKeyEvent>`.
    async fn assemble_signed_events(
        &mut self,
        events: Vec<KeyEvent>,
    ) -> Result<Vec<SignedKeyEvent>, KelsError> {
        if events.is_empty() {
            return Ok(vec![]);
        }
        let saids: Vec<String> = events.iter().map(|e| e.said.clone()).collect();
        let query =
            Query::<EventSignature>::for_table(self.signatures_table).r#in("event_said", saids);
        let signatures: Vec<EventSignature> = self.tx.fetch(query).await?;
        let mut sig_map: HashMap<String, Vec<EventSignature>> = HashMap::new();
        for sig in signatures {
            sig_map.entry(sig.event_said.clone()).or_default().push(sig);
        }
        zip_events_with_signatures(events, &sig_map)
    }

    // ==================== Query methods ====================

    /// Get a paginated page of signed events starting from `since_serial`.
    /// Returns `(events, has_more)` using the limit+1 pop pattern.
    pub async fn get_signed_history_since(
        &mut self,
        since_serial: u64,
        limit: u64,
    ) -> Result<(Vec<SignedKeyEvent>, bool), KelsError> {
        let clamped_limit = limit.min(crate::page_size() as u64);
        let query = Query::<KeyEvent>::for_table(self.events_table)
            .eq("prefix", &self.prefix)
            .gte("serial", since_serial)
            .order_by("serial", Order::Asc)
            .order_by_case("kind", &EventKind::sort_priority_mapping(), Order::Asc)
            .order_by("said", Order::Asc)
            .limit(clamped_limit + 1);
        let mut events: Vec<KeyEvent> = self.tx.fetch(query).await?;

        let has_more = events.len() > clamped_limit as usize;
        if has_more {
            events.pop();
        }

        if events.is_empty() {
            return Ok((vec![], false));
        }

        let result = self.assemble_signed_events(events).await?;
        Ok((result, has_more))
    }

    /// Check which of the given SAIDs already exist in the database.
    pub async fn existing_saids(&mut self, saids: &[String]) -> Result<HashSet<String>, KelsError> {
        if saids.is_empty() {
            return Ok(HashSet::new());
        }
        let query = Query::<KeyEvent>::for_table(self.events_table)
            .eq("prefix", &self.prefix)
            .r#in("said", saids.to_vec());
        let events: Vec<KeyEvent> = self.tx.fetch(query).await?;
        Ok(events.into_iter().map(|e| e.said).collect())
    }

    /// Get a single signed event by SAID.
    pub async fn get_event_by_said(
        &mut self,
        said: &str,
    ) -> Result<Option<SignedKeyEvent>, KelsError> {
        let query = Query::<KeyEvent>::for_table(self.events_table)
            .eq("prefix", &self.prefix)
            .eq("said", said)
            .limit(1);
        let events: Vec<KeyEvent> = self.tx.fetch(query).await?;

        let Some(event) = events.into_iter().next() else {
            return Ok(None);
        };

        Ok(Some(self.assemble_signed_event(event).await?))
    }

    /// Get the last establishment event at or before a given serial.
    pub async fn get_establishment_at_serial(
        &mut self,
        serial: u64,
    ) -> Result<Option<SignedKeyEvent>, KelsError> {
        let query = Query::<KeyEvent>::for_table(self.events_table)
            .eq("prefix", &self.prefix)
            .lte("serial", serial)
            .r#in("kind", EventKind::establishment_kinds())
            .order_by("serial", Order::Desc)
            .limit(1);
        let events: Vec<KeyEvent> = self.tx.fetch(query).await?;

        let Some(event) = events.into_iter().next() else {
            return Ok(None);
        };

        Ok(Some(self.assemble_signed_event(event).await?))
    }

    /// Check if any event from `since_serial` onward reveals the recovery key.
    /// Single query — no pagination needed.
    pub async fn has_recovery_revealing_events_since(
        &mut self,
        since_serial: u64,
    ) -> Result<bool, KelsError> {
        let query = Query::<KeyEvent>::for_table(self.events_table)
            .eq("prefix", &self.prefix)
            .gte("serial", since_serial)
            .r#in("kind", EventKind::recovery_revealing_kinds())
            .limit(1);
        let events: Vec<KeyEvent> = self.tx.fetch(query).await?;
        Ok(!events.is_empty())
    }

    // ==================== Write methods ====================

    /// Insert a signed event and its signatures.
    pub async fn insert_signed_event(
        &mut self,
        signed_event: &SignedKeyEvent,
    ) -> Result<(), KelsError> {
        self.tx
            .insert_with_table(&signed_event.event, self.events_table)
            .await?;
        for sig in signed_event.event_signatures() {
            let mut event_sig: EventSignature = sig;
            event_sig.derive_said()?;
            self.tx
                .insert_with_table(&event_sig, self.signatures_table)
                .await?;
        }
        Ok(())
    }

    /// Delete events by SAID.
    pub async fn delete_events_by_said(&mut self, saids: Vec<String>) -> Result<u64, KelsError> {
        if saids.is_empty() {
            return Ok(0);
        }
        let delete = Delete::<KeyEvent>::for_table(self.events_table).r#in("said", saids);
        Ok(self.tx.delete(delete).await?)
    }

    /// Insert an audit record. No-op if no audit table is configured.
    pub async fn insert_audit_record(&mut self, record: &KelsAuditRecord) -> Result<(), KelsError> {
        if let Some(audit_table) = self.audit_table {
            self.tx.insert_with_table(record, audit_table).await?;
        }
        Ok(())
    }

    /// Load a page of signed events by offset.
    pub async fn load(
        &mut self,
        limit: u64,
        offset: u64,
    ) -> Result<(Vec<SignedKeyEvent>, bool), KelsError> {
        load_signed_history(
            &mut self.tx,
            self.events_table,
            self.signatures_table,
            &self.prefix,
            limit,
            offset,
        )
        .await
    }

    /// Commit the transaction, releasing the advisory lock.
    pub async fn commit(self) -> Result<(), KelsError> {
        self.tx
            .commit()
            .await
            .map_err(|e| KelsError::StorageError(e.to_string()))
    }

    /// Rollback the transaction, releasing the advisory lock.
    pub async fn rollback(self) -> Result<(), KelsError> {
        self.tx
            .rollback()
            .await
            .map_err(|e| KelsError::StorageError(e.to_string()))
    }

    // ==================== Main merge method ====================

    /// Merge submitted events into the existing KEL.
    ///
    /// Performs full verification, divergence detection, and handles recovery,
    /// contest, and adversary archival. This is the single entry point for all
    /// write paths.
    ///
    /// Returns [`MergeOutcome`] on success, [`KelsError`] on validation/verification
    /// failure (transaction should be rolled back).
    pub async fn merge_events(
        &mut self,
        events: &[SignedKeyEvent],
    ) -> Result<MergeOutcome, KelsError> {
        if events.is_empty() {
            return Ok(MergeOutcome::empty());
        }

        // Validate all events belong to this prefix
        for event in events {
            if event.event.prefix != self.prefix {
                return Err(KelsError::InvalidKeyEvent(
                    "All events must have the same prefix".to_string(),
                ));
            }
        }

        // Validate signatures upfront
        for signed_event in events {
            if signed_event.signatures.is_empty() {
                return Err(KelsError::InvalidSignature(
                    "Event missing signature".to_string(),
                ));
            }
            for sig in &signed_event.signatures {
                Signature::from_qb64(&sig.signature).map_err(|e| {
                    KelsError::InvalidSignature(format!("Invalid signature format: {}", e))
                })?;
            }
            if signed_event.event.requires_dual_signature() && signed_event.signatures.len() < 2 {
                return Err(KelsError::InvalidSignature(
                    "Dual signatures required for recovery event".to_string(),
                ));
            }
        }

        let prefix = self.prefix.clone();

        // Re-verify the entire KEL on every submission. We cannot cache KelVerification
        // tokens because the DB cannot be trusted (verification invariant).
        let kel_verification = completed_verification(
            self,
            &prefix,
            crate::page_size(),
            crate::max_pages(),
            iter::empty(),
        )
        .await
        .map_err(|e| KelsError::VerificationFailed(format!("KEL verification failed: {}", e)))?;

        debug!(
            "merge_events: prefix={}, submitted={} events, branches={}, contested={}, diverged_at={:?}",
            prefix,
            events.len(),
            kel_verification.branch_tips().len(),
            kel_verification.is_contested(),
            kel_verification.diverged_at_serial(),
        );

        // Validate event structure
        for signed_event in events {
            signed_event.event.validate_structure().map_err(|e| {
                KelsError::InvalidKeyEvent(format!("Invalid event structure: {}", e))
            })?;
        }

        // Route based on verified context
        let first_previous = events[0].event.previous.clone();
        let is_normal_append = kel_verification.branch_tips().len() == 1
            && first_previous.as_deref()
                == Some(kel_verification.branch_tips()[0].tip.event.said.as_str())
            && !kel_verification.is_contested();

        if is_normal_append {
            self.handle_normal_append(&kel_verification, events).await
        } else if kel_verification.is_empty() && first_previous.is_none() {
            self.handle_new_kel(events).await
        } else {
            self.handle_full_path(&kel_verification, events, &prefix)
                .await
        }
    }

    // ==================== Merge routing ====================

    /// Normal append to a non-divergent KEL (~99% of submissions).
    async fn handle_normal_append(
        &mut self,
        kel_verification: &KelVerification,
        events: &[SignedKeyEvent],
    ) -> Result<MergeOutcome, KelsError> {
        if kel_verification.is_decommissioned() {
            return Err(KelsError::KelDecommissioned);
        }
        if events[0].event.is_contest() {
            return Err(KelsError::InvalidKeyEvent(
                "Contest requires divergence".to_string(),
            ));
        }

        let prefix = &self.prefix;
        let mut verifier = KelVerifier::resume(prefix, kel_verification).map_err(|e| {
            KelsError::VerificationFailed(format!("KEL verification failed: {}", e))
        })?;
        verifier
            .verify_page(events)
            .map_err(|e| KelsError::VerificationFailed(format!("KEL merge failed: {}", e)))?;

        let tip = events.last().map(|e| e.event.said.clone());
        for event in events {
            self.insert_signed_event(event).await?;
        }

        Ok(MergeOutcome {
            result: KelMergeResult::Accepted,
            diverged_at: None,
            tip_said: tip,
        })
    }

    /// New KEL (inception).
    async fn handle_new_kel(
        &mut self,
        events: &[SignedKeyEvent],
    ) -> Result<MergeOutcome, KelsError> {
        let prefix = &self.prefix;
        let mut verifier = KelVerifier::new(prefix);
        verifier
            .verify_page(events)
            .map_err(|e| KelsError::VerificationFailed(format!("KEL merge failed: {}", e)))?;

        let tip = events.last().map(|e| e.event.said.clone());
        for event in events {
            self.insert_signed_event(event).await?;
        }

        Ok(MergeOutcome {
            result: KelMergeResult::Accepted,
            diverged_at: None,
            tip_said: tip,
        })
    }

    /// Full path: divergence, recovery, overlap (rare).
    async fn handle_full_path(
        &mut self,
        kel_verification: &KelVerification,
        events: &[SignedKeyEvent],
        prefix: &str,
    ) -> Result<MergeOutcome, KelsError> {
        // Contested KELs reject all submissions
        if kel_verification.is_contested() {
            return Err(KelsError::ContestedKel(
                "KEL is already contested".to_string(),
            ));
        }

        // Filter duplicates
        let submitted_saids: Vec<String> = events.iter().map(|e| e.event.said.clone()).collect();
        let existing = self.existing_saids(&submitted_saids).await?;
        let new_events: Vec<SignedKeyEvent> = events
            .iter()
            .filter(|e| !existing.contains(&e.event.said))
            .cloned()
            .collect();

        if new_events.is_empty() {
            return Ok(MergeOutcome {
                result: KelMergeResult::Accepted,
                diverged_at: kel_verification.diverged_at_serial(),
                tip_said: None,
            });
        }

        // Re-route after dedup
        let new_first_previous = new_events[0].event.previous.as_deref();

        if new_first_previous.is_none() {
            return Err(KelsError::InvalidKeyEvent(
                "Inception event SAID mismatch".to_string(),
            ));
        }

        // Check if dedup turned this into a normal append
        if !kel_verification.is_divergent()
            && kel_verification.branch_tips().len() == 1
            && new_first_previous == Some(kel_verification.branch_tips()[0].tip.event.said.as_str())
        {
            let mut verifier = KelVerifier::resume(prefix, kel_verification).map_err(|e| {
                KelsError::VerificationFailed(format!("KEL verification failed: {}", e))
            })?;
            verifier
                .verify_page(&new_events)
                .map_err(|e| KelsError::VerificationFailed(format!("KEL merge failed: {}", e)))?;
            let tip = new_events.last().map(|e| e.event.said.clone());
            for event in &new_events {
                self.insert_signed_event(event).await?;
            }
            return Ok(MergeOutcome {
                result: KelMergeResult::Accepted,
                diverged_at: None,
                tip_said: tip,
            });
        }

        if kel_verification.is_divergent() {
            let (result, diverged_at) = self
                .handle_divergent_submission(kel_verification, &new_events, prefix)
                .await?;
            Ok(MergeOutcome {
                result,
                diverged_at,
                tip_said: None,
            })
        } else {
            let (result, diverged_at) = self
                .handle_overlap_submission(kel_verification, &new_events, prefix)
                .await?;
            Ok(MergeOutcome {
                result,
                diverged_at,
                tip_said: None,
            })
        }
    }

    // ==================== Full merge path helpers ====================

    /// Handle submission to an already-divergent KEL.
    async fn handle_divergent_submission(
        &mut self,
        kel_verification: &KelVerification,
        new_events: &[SignedKeyEvent],
        prefix: &str,
    ) -> Result<(KelMergeResult, Option<u64>), KelsError> {
        let Some(diverged_at) = kel_verification.diverged_at_serial() else {
            return Err(KelsError::StorageError(
                "Divergent KEL missing diverged_at_serial".to_string(),
            ));
        };

        let first = &new_events[0];

        // === Contest ===
        if first.event.is_contest() {
            if new_events.len() > 1 {
                return Err(KelsError::InvalidKeyEvent(
                    "Cannot append events after contest".to_string(),
                ));
            }

            if kel_verification.is_contested() {
                return Err(KelsError::ContestedKel(
                    "KEL is already contested".to_string(),
                ));
            }

            let cnt_serial = first.event.serial;
            if cnt_serial == 0 {
                return Err(KelsError::InvalidKeyEvent(
                    "Contest cannot have serial 0".to_string(),
                ));
            }
            if !self.non_contest_recovery_revealed_since(cnt_serial).await? {
                return Err(KelsError::VerificationFailed(
                    "KEL is frozen — no recovery key revealed".to_string(),
                ));
            }

            let full_kel_verification = completed_verification(
                self,
                prefix,
                crate::page_size(),
                crate::max_pages(),
                iter::empty::<String>(),
            )
            .await
            .map_err(|e| {
                KelsError::VerificationFailed(format!("KEL verification failed: {}", e))
            })?;

            let contest_previous = first.event.previous.as_deref().ok_or_else(|| {
                KelsError::InvalidKeyEvent("Contest has no previous pointer".to_string())
            })?;
            let anchor_event =
                self.get_event_by_said(contest_previous)
                    .await?
                    .ok_or_else(|| {
                        KelsError::InvalidKeyEvent(
                            "Contest does not extend a known event".to_string(),
                        )
                    })?;
            if anchor_event.event.serial != cnt_serial - 1 {
                return Err(KelsError::InvalidKeyEvent(
                    "Contest previous event is not at the expected serial".to_string(),
                ));
            }

            let mut verifier =
                KelVerifier::resume(prefix, &full_kel_verification).map_err(|e| {
                    KelsError::VerificationFailed(format!("KEL verification failed: {}", e))
                })?;
            verifier
                .verify_page(slice::from_ref(first))
                .map_err(|e| KelsError::VerificationFailed(format!("KEL merge failed: {}", e)))?;

            self.insert_signed_event(first).await?;
            return Ok((KelMergeResult::Contested, Some(diverged_at)));
        }

        // === Recovery (rec event anywhere in batch) ===
        if let Some(rec_idx) = new_events.iter().position(|e| e.event.is_recover()) {
            let rec_event = &new_events[rec_idx];

            let first_serial = new_events[0].event.serial;

            if self
                .has_recovery_revealing_events_since(first_serial)
                .await?
            {
                return Err(KelsError::ContestRequired);
            }

            self.verify_chain_before_serial(prefix, first_serial)
                .await?;

            let first_previous = new_events[0].event.previous.as_deref().ok_or_else(|| {
                KelsError::InvalidKeyEvent("Event has no previous pointer".to_string())
            })?;

            let anchor_event = self
                .get_event_by_said(first_previous)
                .await?
                .ok_or_else(|| {
                    KelsError::InvalidKeyEvent("Recovery does not extend a known event".to_string())
                })?;
            if anchor_event.event.serial >= first_serial {
                return Err(KelsError::InvalidKeyEvent(
                    "Recovery chain-from event is not before first submitted serial".to_string(),
                ));
            }

            let establishment = self
                .trace_establishment_backward(&anchor_event.event.said)
                .await?;
            let anchor_tip = BranchTip {
                tip: anchor_event,
                establishment_tip: establishment,
            };

            let mut event_verifier =
                KelVerifier::from_branch_tip(prefix, &anchor_tip).map_err(|e| {
                    KelsError::VerificationFailed(format!("KEL verification failed: {}", e))
                })?;
            event_verifier
                .verify_page(new_events)
                .map_err(|e| KelsError::VerificationFailed(format!("KEL merge failed: {}", e)))?;

            let rec_previous = rec_event.event.previous.as_deref().ok_or_else(|| {
                KelsError::InvalidKeyEvent("Recovery event has no previous".to_string())
            })?;

            // Archive adversary events BEFORE inserting any new events. Inserting
            // pre_rec events first would create a temporary 3-event-at-same-serial
            // state when the owner's pre_rec event is at the divergence serial
            // (e.g., ror@1 when both events at serial 1 are adversary).
            self.check_contest_and_archive_adversary(first_serial, diverged_at, rec_previous)
                .await?;

            for event in new_events {
                self.insert_signed_event(event).await?;
            }

            return Ok((KelMergeResult::Recovered, None));
        }

        // Neither contest nor recovery — frozen KEL rejects non-recovery submissions
        Ok((KelMergeResult::RecoverRequired, Some(diverged_at)))
    }

    /// Handle submission that overlaps with or creates new divergence in a non-divergent KEL.
    async fn handle_overlap_submission(
        &mut self,
        kel_verification: &KelVerification,
        new_events: &[SignedKeyEvent],
        prefix: &str,
    ) -> Result<(KelMergeResult, Option<u64>), KelsError> {
        if kel_verification.is_divergent() || kel_verification.is_contested() {
            return Err(KelsError::StorageError(
                "handle_overlap_submission called with divergent or contested KEL".to_string(),
            ));
        }

        let first_previous = new_events[0].event.previous.as_deref().ok_or_else(|| {
            KelsError::InvalidKeyEvent("Inception event SAID mismatch".to_string())
        })?;

        let branch_point = self
            .get_event_by_said(first_previous)
            .await?
            .ok_or_else(|| KelsError::InvalidKeyEvent("Events not contiguous".to_string()))?;

        let branch_serial = branch_point.event.serial;

        let establishment = self
            .get_establishment_at_serial(branch_serial)
            .await?
            .ok_or_else(|| {
                KelsError::StorageError("No establishment event found at branch point".to_string())
            })?;

        let branch_tip = BranchTip {
            tip: branch_point,
            establishment_tip: establishment,
        };

        let mut verifier = KelVerifier::from_branch_tip(prefix, &branch_tip).map_err(|e| {
            KelsError::VerificationFailed(format!("KEL verification failed: {}", e))
        })?;
        verifier
            .verify_page(new_events)
            .map_err(|e| KelsError::VerificationFailed(format!("KEL merge failed: {}", e)))?;

        // Check if any existing event from divergence onward reveals recovery key
        let diverged_at = branch_serial + 1;
        let old_reveals_recovery = self
            .has_recovery_revealing_events_since(diverged_at)
            .await?;

        if old_reveals_recovery {
            let divergent_event = new_events
                .iter()
                .find(|e| e.event.previous.as_deref() == Some(first_previous))
                .ok_or_else(|| {
                    KelsError::InvalidKeyEvent("Cannot find divergent event".to_string())
                })?;

            if divergent_event.event.is_contest() {
                if new_events.len() > 1 {
                    return Err(KelsError::InvalidKeyEvent(
                        "Cannot append events after contest".to_string(),
                    ));
                }
                self.insert_signed_event(divergent_event).await?;
                return Ok((KelMergeResult::Contested, Some(branch_serial + 1)));
            } else {
                return Err(KelsError::ContestRequired);
            }
        }

        // Check for recovery in submitted events
        if let Some(rec_idx) = new_events.iter().position(|e| e.event.is_recover()) {
            let pre_rec = &new_events[..rec_idx];
            let post_rec = &new_events[rec_idx..];
            let rec_event = &new_events[rec_idx];

            for event in pre_rec {
                self.insert_signed_event(event).await?;
            }

            let rec_previous = rec_event.event.previous.as_deref().ok_or_else(|| {
                KelsError::InvalidKeyEvent("Recovery event has no previous".to_string())
            })?;

            self.check_contest_and_archive_adversary(
                rec_event.event.serial,
                diverged_at,
                rec_previous,
            )
            .await?;

            for event in post_rec {
                self.insert_signed_event(event).await?;
            }

            return Ok((KelMergeResult::Recovered, None));
        }

        // No recovery event — insert single forking event to establish divergence
        let divergent_event = new_events
            .iter()
            .find(|e| e.event.previous.as_deref() == Some(first_previous))
            .ok_or_else(|| KelsError::InvalidKeyEvent("Cannot find divergent event".to_string()))?;

        self.insert_signed_event(divergent_event).await?;

        Ok((KelMergeResult::Diverged, Some(branch_serial + 1)))
    }

    // ==================== Scan helpers ====================

    /// Identify the adversary event at the divergence point.
    ///
    /// A divergent KEL has exactly 2 events at the divergence serial, with one
    /// branch always exactly 1 event long. The recovery/contest event's
    /// `previous` chain identifies the owner's side; the other is the adversary.
    ///
    /// 1. If `rec_previous` matches a divergent event SAID → the other is the adversary.
    /// 2. Otherwise (N case): query for events whose `previous` points to a
    ///    divergent event. The divergent event with no child is the adversary.
    ///
    /// Returns `(adversary_event, adversary_has_chain)`.
    async fn find_adversary_event(
        &mut self,
        diverged_at: u64,
        rec_previous: &str,
    ) -> Result<(SignedKeyEvent, bool), KelsError> {
        let (events, _) = self
            .get_signed_history_since(diverged_at, crate::page_size() as u64)
            .await?;
        // Validate divergence invariant: exactly one serial has 2 events,
        // all others have 1. Rejects tampered DBs with extra injected events.
        let mut serial_counts: HashMap<u64, usize> = HashMap::new();
        for event in &events {
            *serial_counts.entry(event.event.serial).or_default() += 1;
        }
        for (&serial, &count) in &serial_counts {
            if serial == diverged_at {
                if count != 2 {
                    return Err(KelsError::StorageError(format!(
                        "Expected 2 events at divergence serial {}, found {}",
                        diverged_at, count
                    )));
                }
            } else if count > 1 {
                return Err(KelsError::StorageError(format!(
                    "Unexpected duplicate events at serial {} (expected only at {})",
                    serial, diverged_at
                )));
            }
        }

        let divergent: Vec<&SignedKeyEvent> = events
            .iter()
            .filter(|e| e.event.serial == diverged_at)
            .collect();

        // Check if either divergent event has a child on this page. Safe from
        // page boundary issues: the page starts at diverged_at, so the 2 divergent
        // events are positions 1-2 and a child at diverged_at+1 is position 3.
        let d0 = &divergent[0].event.said;
        let d1 = &divergent[1].event.said;
        let d0_has_child = events
            .iter()
            .any(|e| e.event.serial > diverged_at && e.event.previous.as_deref() == Some(d0));
        let d1_has_child = events
            .iter()
            .any(|e| e.event.serial > diverged_at && e.event.previous.as_deref() == Some(d1));

        // Direct match: rec/cnt previous points to one of the divergent events
        if rec_previous == divergent[0].event.said {
            return Ok((divergent[1].clone(), d1_has_child));
        }
        if rec_previous == divergent[1].event.said {
            return Ok((divergent[0].clone(), d0_has_child));
        }

        // N case: rec extends a chain. The divergent event WITHOUT a child
        // at the next serial is the adversary's single event (never has chain).
        match (d0_has_child, d1_has_child) {
            (true, false) => Ok((divergent[1].clone(), false)),
            (false, true) => Ok((divergent[0].clone(), false)),
            _ => Err(KelsError::StorageError(
                "Cannot identify adversary event at divergence point".to_string(),
            )),
        }
    }

    /// Archive the adversary's entire chain starting from their event at the
    /// divergence serial. Pages forward, identifying chain events by following
    /// `previous` pointers from the adversary event. Audits and deletes
    /// adversary events page by page. The adversary event itself is prepended
    /// to the first page.
    ///
    /// Callers must check `has_recovery_revealing_events_since` before calling
    /// this method to determine if `ContestRequired` should be returned instead.
    async fn archive_adversary_chain(
        &mut self,
        adversary_event: SignedKeyEvent,
        diverged_at: u64,
    ) -> Result<(), KelsError> {
        let max_pages = crate::max_pages();
        let mut last_adversary_said = adversary_event.event.said.clone();

        let mut from_serial = diverged_at + 1;
        let mut first_page = true;

        for _ in 0..max_pages {
            let (page, has_more) = self
                .get_signed_history_since(from_serial, crate::page_size() as u64)
                .await?;

            let mut page_adversary: Vec<SignedKeyEvent> = Vec::new();
            if first_page {
                page_adversary.push(adversary_event.clone());
                first_page = false;
            }

            for event in &page {
                if event.event.previous.as_deref() == Some(last_adversary_said.as_str()) {
                    last_adversary_said = event.event.said.clone();
                    page_adversary.push(event.clone());
                }
            }

            if !page_adversary.is_empty() {
                let audit_record =
                    KelsAuditRecord::for_recovery(self.prefix.clone(), &page_adversary)?;
                self.insert_audit_record(&audit_record).await?;
                let saids: Vec<String> = page_adversary
                    .iter()
                    .map(|e| e.event.said.clone())
                    .collect();
                self.delete_events_by_said(saids).await?;
            }

            if page.is_empty() || !has_more {
                break;
            }
            if let Some(last) = page.last() {
                from_serial = last.event.serial + 1;
            }
        }

        // If first_page is still true, there were no pages after diverged_at.
        // Just audit+delete the adversary event itself.
        if first_page {
            let audit_record = KelsAuditRecord::for_recovery(
                self.prefix.clone(),
                slice::from_ref(&adversary_event),
            )?;
            self.insert_audit_record(&audit_record).await?;
            self.delete_events_by_said(vec![adversary_event.event.said])
                .await?;
        }

        Ok(())
    }

    /// Archive ALL events from `from_serial` onward. Used when all events at
    /// and after the divergence serial are adversary (owner has no events there).
    /// Audits and deletes page by page.
    async fn archive_all_from_serial(&mut self, from_serial: u64) -> Result<(), KelsError> {
        let max_pages = crate::max_pages();
        let mut serial = from_serial;

        for _ in 0..max_pages {
            let (page, has_more) = self
                .get_signed_history_since(serial, crate::page_size() as u64)
                .await?;

            if page.is_empty() {
                break;
            }

            let audit_record = KelsAuditRecord::for_recovery(self.prefix.clone(), &page)?;
            self.insert_audit_record(&audit_record).await?;
            let saids: Vec<String> = page.iter().map(|e| e.event.said.clone()).collect();
            if let Some(last) = page.last() {
                serial = last.event.serial + 1;
            }
            self.delete_events_by_said(saids).await?;

            if !has_more {
                break;
            }
        }

        Ok(())
    }

    /// Check if the adversary revealed the recovery key and archive adversary
    /// events. Handles both cases: owner has events at the divergence serial
    /// (uses `find_adversary_event`) or owner has no events there (archives all).
    async fn check_contest_and_archive_adversary(
        &mut self,
        first_serial: u64,
        diverged_at: u64,
        rec_previous: &str,
    ) -> Result<(), KelsError> {
        if first_serial <= diverged_at {
            // Owner has no events at the divergence serial — all events
            // from diverged_at onward are adversary.
            if self
                .has_recovery_revealing_events_since(diverged_at)
                .await?
            {
                return Err(KelsError::ContestRequired);
            }
            self.archive_all_from_serial(diverged_at).await
        } else {
            let (adversary, adversary_has_chain) =
                self.find_adversary_event(diverged_at, rec_previous).await?;

            if adversary.event.reveals_recovery_key()
                || (adversary_has_chain
                    && self
                        .has_recovery_revealing_events_since(diverged_at + 1)
                        .await?)
            {
                return Err(KelsError::ContestRequired);
            }

            self.archive_adversary_chain(adversary, diverged_at).await
        }
    }

    /// Walk backward from `start_said` following `previous` pointers until finding
    /// an establishment event.
    async fn trace_establishment_backward(
        &mut self,
        start_said: &str,
    ) -> Result<SignedKeyEvent, KelsError> {
        let max_steps = crate::max_pages() * crate::page_size();
        let mut current_said = Some(start_said.to_string());

        for _ in 0..max_steps {
            let Some(said) = current_said.take() else {
                break;
            };
            let event = self.get_event_by_said(&said).await?.ok_or_else(|| {
                KelsError::StorageError(format!(
                    "Broken chain: event {} not found during establishment trace",
                    said,
                ))
            })?;
            if event.event.is_establishment() {
                return Ok(event);
            }
            current_said = event.event.previous.clone();
        }

        Err(KelsError::StorageError(
            "Backward establishment trace exceeded iteration limit or reached chain start"
                .to_string(),
        ))
    }

    /// Verify a sub-chain from serial 0 up to (but not including) `stop_serial`.
    async fn verify_chain_before_serial(
        &mut self,
        prefix: &str,
        stop_serial: u64,
    ) -> Result<KelVerifier, KelsError> {
        let max_pages = crate::max_pages();
        let mut verifier = KelVerifier::new(prefix);
        let mut from_serial: u64 = 0;
        let page_size = crate::page_size() as u64;

        for _ in 0..max_pages {
            let (page, has_more) = self
                .get_signed_history_since(from_serial, page_size)
                .await?;
            if page.is_empty() {
                return Ok(verifier);
            }

            let filtered: Vec<&SignedKeyEvent> = page
                .iter()
                .filter(|e| e.event.serial < stop_serial)
                .collect();
            if filtered.is_empty() {
                return Ok(verifier);
            }

            let to_verify: Vec<SignedKeyEvent> = filtered.into_iter().cloned().collect();
            verifier.verify_page(&to_verify).map_err(|e| {
                KelsError::VerificationFailed(format!("KEL verification failed: {}", e))
            })?;

            if page.last().is_some_and(|e| e.event.serial >= stop_serial) {
                return Ok(verifier);
            }
            if let Some(last) = page.last() {
                from_serial = last.event.serial + 1;
            }
            if !has_more {
                return Ok(verifier);
            }
        }

        Err(KelsError::StorageError(
            "Scan exceeded max_pages limit — cannot verify sub-chain".to_string(),
        ))
    }

    /// Check if any non-contest event at or after `from_serial` reveals the recovery key.
    async fn non_contest_recovery_revealed_since(
        &mut self,
        from_serial: u64,
    ) -> Result<bool, KelsError> {
        let max_pages = crate::max_pages();
        let mut serial = from_serial;
        for _ in 0..max_pages {
            let (page, has_more) = self
                .get_signed_history_since(serial, crate::page_size() as u64)
                .await?;
            if page.is_empty() {
                return Ok(false);
            }
            if page
                .iter()
                .any(|e| e.event.reveals_recovery_key() && !e.event.is_contest())
            {
                return Ok(true);
            }
            if let Some(last) = page.last() {
                serial = last.event.serial + 1;
            }
            if !has_more {
                return Ok(false);
            }
        }
        Err(KelsError::StorageError(
            "Scan exceeded max_pages limit — cannot determine recovery state".to_string(),
        ))
    }
}

#[async_trait]
impl<T: TransactionExecutor> PageLoader for MergeTransaction<T> {
    async fn load_page(
        &mut self,
        _prefix: &str,
        limit: u64,
        offset: u64,
    ) -> Result<(Vec<SignedKeyEvent>, bool), KelsError> {
        self.load(limit, offset).await
    }
}
