apiVersion: garden.io/v2
kind: Project
name: kels
defaultEnvironment: node-a

environments:
  - name: registry
    defaultNamespace: kels-registry
  - name: node-a
    defaultNamespace: kels-node-a
  - name: node-b
    defaultNamespace: kels-node-b

providers:
  - name: local-kubernetes
    environments: [registry, node-a, node-b]
    namespace:
      name: ${environment.namespace}
    setupIngressController: nginx
    defaultHostname: ${environment.namespace}.local
    buildMode: local-docker

variables:
  registryUrl: "http://kels-registry.kels-registry.svc.cluster.local:80"
  rustLogLevel: info
  postgres:
    user: kels_admin
    password: use_something_better_in_production
    host: postgres
    port: 5432
    url: "postgres://${var.postgres.user}:${var.postgres.password}@${var.postgres.host}:${var.postgres.port}"
  redis:
    host: redis
    port: 6379
    url: "redis://${var.redis.host}:${var.redis.port}"
  kels:
    replicas: 2
    host: kels
    port: "80"
    url: http://${var.kels.host}:${var.kels.port}
  gossip:
    replicas: 1
    port: 4001
    topic: "kels/events/v1"
    listenAddress: "/ip4/0.0.0.0/tcp/${var.gossip.port}"
    # Test-only: delay in ms before broadcasting announcements.
    # Set to "0" for production. Use higher values (e.g., "5000") for adversarial testing.
    testPropagationDelayMs: "0"
  registry:
    replicas: 2
    port: "80"
    heartbeatTimeoutSecs: "60"
