apiVersion: garden.io/v2
kind: Project
name: kels
defaultEnvironment: registry-a

environments:
  - name: registry-a
    defaultNamespace: kels-registry-a
    variables:
      envType: registry
  - name: registry-b
    defaultNamespace: kels-registry-b
    variables:
      envType: registry
  - name: registry-c
    defaultNamespace: kels-registry-c
    variables:
      envType: registry
  - name: node-a
    defaultNamespace: kels-node-a
    variables:
      envType: node
  - name: node-b
    defaultNamespace: kels-node-b
    variables:
      envType: node
  - name: node-c
    defaultNamespace: kels-node-c
    variables:
      envType: node
  - name: node-d
    defaultNamespace: kels-node-d
    variables:
      envType: node

providers:
  - name: local-kubernetes
    environments: [registry-a, registry-b, registry-c, node-a, node-b, node-c, node-d]
    namespace:
      name: ${environment.namespace}
    setupIngressController: nginx
    defaultHostname: ${environment.namespace}.local
    buildMode: local-docker

variables:
  rustLogLevel: info
  postgres:
    user: kels_admin
    password: use_something_better_in_production
    host: postgres
    port: 5432
    url: "postgres://${var.postgres.user}:${var.postgres.password}@${var.postgres.host}:${var.postgres.port}"
  redis:
    host: redis
    port: 6379
    url: "redis://${var.redis.host}:${var.redis.port}"
  kels:
    replicas: 2
    host: kels
    port: "80"
    url: http://${var.kels.host}:${var.kels.port}
  gossip:
    replicas: 1
    port: 4001
    topic: "kels/events/v1"
    listenAddress: "/ip4/0.0.0.0/tcp/${var.gossip.port}"
    # Test-only: delay in ms before broadcasting announcements.
    # Set to "0" for production. Use higher values (e.g., "5000") for adversarial testing.
    testPropagationDelayMs: "0"
    # Allow starting without TRUSTED_REGISTRIES (for bootstrapping first node)
    allowBootstrapMode: "false"
  registry:
    replicas: 1
    port: "80"
    heartbeatTimeoutSecs: "60"
  hsm:
    port: "80"
    host: hsm
    url: http://${var.hsm.host}:${var.hsm.port}
  identity:
    port: "80"
    host: identity
    url: http://${var.identity.host}:${var.identity.port}
