apiVersion: garden.io/v2
kind: Project
name: kels
defaultEnvironment: registry-a

environments:
  - name: registry-a
    defaultNamespace: kels-registry-a
    variables:
      envType: registry
  - name: registry-b
    defaultNamespace: kels-registry-b
    variables:
      envType: registry
  - name: registry-c
    defaultNamespace: kels-registry-c
    variables:
      envType: registry
  - name: registry-d
    defaultNamespace: kels-registry-d
    variables:
      envType: registry
  - name: node-a
    defaultNamespace: kels-node-a
    variables:
      envType: node
      devTools: true # testing
      gossipResyncIntervalSecs: "15" # testing
      nodeType: core
  - name: node-b
    defaultNamespace: kels-node-b
    variables:
      envType: node
      devTools: true # testing
      nodeType: core
  - name: node-c
    defaultNamespace: kels-node-c
    variables:
      envType: node
      devTools: false
      nodeType: core
  - name: node-d
    defaultNamespace: kels-node-d
    variables:
      envType: node
      devTools: true # testing
      nodeType: regional
  - name: node-e
    defaultNamespace: kels-node-e
    variables:
      envType: node
      devTools: false
      nodeType: regional
  - name: node-f
    defaultNamespace: kels-node-f
    variables:
      envType: node
      devTools: false
      nodeType: regional

providers:
  - name: local-kubernetes
    environments: [registry-a, registry-b, registry-c, registry-d, node-a, node-b, node-c, node-d, node-e, node-f]
    namespace:
      name: ${environment.namespace}
    setupIngressController: nginx
    defaultHostname: ${environment.namespace}.kels
    buildMode: local-docker

variables:
  gossipResyncIntervalSecs: "${var.gossip.resyncIntervalSecs}"
  rustLogLevel: debug
  postgres:
    user: kels_admin
    password: use_something_better_in_production
    host: postgres
    port: 5432
    url: "postgres://${var.postgres.user}:${var.postgres.password}@${var.postgres.host}:${var.postgres.port}"
  redis:
    host: redis
    port: 6379
    url: "redis://${var.redis.host}:${var.redis.port}"
  kels:
    replicas: 2
    host: kels
    port: "80"
    url: http://${var.kels.host}:${var.kels.port}
  gossip:
    replicas: 1
    port: 4001
    httpListenHost: "0.0.0.0"
    httpPort: "80"
    topic: "kels/events/v1"
    listenAddress: "0.0.0.0:${var.gossip.port}"
    resyncIntervalSecs: "300"
  registry:
    replicas: 1
    port: "80"
    heartbeatTimeoutSecs: "60"
  hsm:
    port: "80"
    host: hsm
    url: http://${var.hsm.host}:${var.hsm.port}
  identity:
    port: "80"
    host: identity
    url: http://${var.identity.host}:${var.identity.port}
